config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :pets, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:index, :show, :new, :create, :edit, :update]
  end
  resources :users, only: [:show, :edit, :update]
  resources :bookings, only: [:destroy]



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :pet
end

app/models/pet.rb
class Pet < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  has_many :bookings


  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  validates :name, presence: true
  validates :species, presence: true, inclusion: { in: ["cat", "dog", "turtle", "rabbit", "hamster", "mouse", "bird", "fish", "other"]}
  validates :age, presence: true, inclusion: 0..100
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
  has_many :pets
  has_many :bookings

  validates :name, presence: true, uniqueness: true
  validates :location, presence: true
  validates :bio, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # include CloudinaryHelper
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :location, :bio, :photo])


  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
    @bookings = Booking.all

  end

  def new
    @booking = Booking.new
    @pet = Pet.find(params[:pet_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @pet = Pet.find(params[:pet_id])
    @booking.user = current_user
    @booking.pet = @pet

    if @booking.save!
      redirect_to pet_booking_path(pet_id: @pet, id: @booking)
    else
      render "new"
    end
  end

  def edit
     @booking = Booking.find(params[:id])
     @pet = Pet.find(params[:pet_id])
  end

  def update
    @booking = Booking.find(params[:id])
    @pet = Pet.find(params[:pet_id])
    @booking.user = current_user
    @booking.pet = @pet
    @booking.update(booking_params)

    if @booking.save!
      redirect_to pet_booking_path(pet_id: @pet, id: @booking)
    else
      render "edit"
    end
  end

  def destroy

  @booking = Booking.find(params[:id])
  @booking.destroy

  redirect_to user_path(@booking.user)

  end

  private

    def booking_params
      params.require(:booking).permit(:start_date, :end_date, :pet_id, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
skip_before_action :authenticate_user!, only: :home

  def home

  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all


     # the `geocoded` scope filters only flats with coordinates (latitude & longitude)
    @markers = @pets.geocoded.map do |pet|
      {
        lat: pet.latitude,
        lng: pet.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { pet: pet }),
      }
    end

    if params[:species].present? && params[:species] != "all"
      @pets = @pets.where(species: params[:species])
    end
    if params[:age].present?
      @pets = @pets.where("age <= ?", params[:age])
    end
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    if @pet.save
      redirect_to pets_path
    else
      render :new
    end
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :species, :age, :description, :location, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @pets = @user.pets
    @bookings = @user.bookings
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  private

  def user_params
  params.require(:user).permit(:name, :locaction, :bio)

  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_index.html.erb
<div class="container">

  <div class="text-center">
    <h1>All your bookings</h1>
  </div>
    <div class="card mt-5 mb-5" >
      <ul class="list-group list-group-flush">
      <% @bookings.each do |b| %>
          <% if b.user === current_user %>
              <li class="list-group-item"> <p><%= b.pet.name %> the <%= b.pet.species %> is booked between <strong><%= b.start_date %> </strong> and <strong><%= b.end_date %></strong></p> | <%= link_to 'edit' %> <%= link_to 'delete'%></li>
          <% end %>
      <% end %>
  </ul>
  </div>
</div>

app/views/bookings/edit.html.erb
<div class="container">
  <h1 class="text-center">Change your booking</h1>

  <%= simple_form_for [@pet, @booking] do |f| %>
    <%= f.input :start_date, html5: true %>
    <%= f.input :end_date, html5: true %>
    <%= f.button :submit, "Change", class: "btn-confirm" %>
  <% end %>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <div class="text-center">
    <h1>Your bookings</h1>
  </div>
  <div>
    <%= @bookings.each do |b| %>
      <ol>
        <li> <%= b.id %> </li>
        <li> <%= b.pet.name %> </li>
        <li> <%= b.start_date.strftime("%H:%M") %> </li>
        <li> <%= b.end_date.strftime("%H:%M") %> </li>
      </ol>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="text-center">
    <h1>New booking</h1>
  </div>

  <div>
    <%= simple_form_for [@pet, @booking] do |f| %>
      <%= f.input :start_date, html5: true %>
      <%= f.input :end_date, html5: true %>

      <%= f.button :submit, "Book", class: "btn-confirm" %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <h1>Booking details</h1>
  <br>
  <br>
  <h3>Your booking with <strong><%= @booking.pet.name.upcase %></strong></h3>
  <br>
  <div class="card-product">
  <div class="card-product-infos">
      <p><strong>Time: </strong>from <em><%= @booking.start_date.strftime("%H:%M") %></em> to <em><%= @booking.end_date.strftime("%H:%M") %></em></p>
      <p>Booked by: <em><%= link_to @booking.user.name, '#' %></em></p>
  </div>
  </div>
  <br>
  <br>
  <div class="d-line">
    <%= link_to 'Confirm', user_path(current_user), class: 'btn-confirm' %>
    <%= link_to 'Back', :back, class: 'btn' %>
  </div>
  <br>
  <br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<meta name="og:title" content="PETogether" />
    <meta name="og:type" content="Resume Website" />
    <meta name="og:locale" content="en_IN" />
    <meta property="og:image" content="%PUBLIC_URL%/favicon-32x32.png" />
    <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
    <title>THEPetClub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>

    <%= render 'shared/flashes' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<header class="masthead text-center">
  <div class="container d-flex align-items-center flex-column">
      <!-- Masthead Avatar Image-->
      <%= link_to do %>
      <a class="masthead-heading mb-0" href="/pets"><img class="masthead-avatar mb-5" src="https://i.pinimg.com/originals/0c/27/2b/0c272bc26c77c72e88f2502248645b40.png" alt="kitten" width="400px" height="450px" /></a>
      <!-- Masthead Heading-->
        <a class="masthead-heading mb-0" href="/pets">PETogether</a>      <!-- Icon Divider-->
      <% end %>
<!--       <div class="divider-custom divider-light">
          <div class="divider-custom-line"></div>
          <div class="divider-custom-line"></div>
          <div class="divider-custom-line"></div>
      </div> -->
      <!-- Masthead Subheading-->
      <p class="masthead-subheading font-weight-light mb-0">Book a time with pets near you!</p>
      <br>
      <br>
  </div>
</header>

app/views/pets/_info_window.html.erb
<h2><%= pet.name %></h2>
<p><%= pet.location %></p>
<%= cl_image_tag pet.photo.key %>

app/views/pets/create.html.erb
<h1>Pets#create</h1>
<p>Find me in app/views/pets/create.html.erb</p>

app/views/pets/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url(https://source.unsplash.com/qO-PIF84Vxg/100%);">
  <div class="container">
    <h1>Find your match</h1>
    <p>Take us out for a walk if you miss having an animal of your own or find someone to walk your pet.</p>
    <%= link_to "Post a pet", new_pet_path, class: "btn btn-post btn-lg" %>
  </div>
</div>

<div class="container">


<div id="map"
     style="width: 100%; height: 300px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>


  <div class="cards mt-3">
    <%= form_tag pets_path, method: :get do %>
    <%= select_tag :species, options_for_select([ "all", "cat", "dog", "turtle", "rabbit", "hamster", "mouse", "bird", "fish", "other"]) %>
    <div id="range-field-value">
      pets up to 100 years old
    </div>
    <%= range_field_tag(:age, value = 100, options = {class: "pet-range-input", min: 0, max: 100}) %>
    <%= submit_tag "Search", class: "btn-confirm" %>
  <% end %>
  </div>


    <div class="cards mt-4">
      <% @pets.each do |pet| %>
      <%= link_to pet_path(pet) do %>
          <div class="card-trip">
            <div class="card-trip-infos">
              <div>
                <h3><%= pet.name %></h3>
                <p>I am a <%= pet.species %>!</p>
                <p>"<%= pet.description.first(30) %>..."</p>
                <p><%= pet.location %></p>
                 <%= cl_image_tag pet.photo.key, height: 200, width:350, crop: :fill %>
              </div>
            </div>
          </div>
          <% end %>
      <% end %>
  </div>

</div>





<!--
<div>
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Species
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
      <button class="dropdown-item" type="button">Dogs</button>
      <button class="dropdown-item" type="button">Cats</button>
      <button class="dropdown-item" type="button">Other</button>
    </div>
  </div>


  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Location
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
      <button class="dropdown-item" type="button">Stockholm</button>
      <button class="dropdown-item" type="button">Uppsala</button>
      <button class="dropdown-item" type="button">Malmö</button>
    </div>
  </div>



  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Date
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
      <button class="dropdown-item" type="button">Week 1 </button>
      <button class="dropdown-item" type="button">Week 2</button>
      <button class="dropdown-item" type="button">Week 3</button>
    </div>
  </div>
</div>

 -->

app/views/pets/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/YCPkW_r_6uA/100%);">
  <div class="container">
    <h2>Add a new friend!</h2>
    <p>We are exciting to meet a new friend <i class="fas fa-heart"></i></p>
  </div>
</div>

<div class="container">
  <div>
    <%= simple_form_for @pet do |f| %>
          <%= f.input :name %>
          <%= f.input :species, collection: ["cat", "dog", "turtle", "rabbit", "hamster", "mouse", "bird", "fish", "other"] %>
          <%= f.input :age%>
          <%= f.input :location%>
          <%= f.input :description %>
          <%= f.input :photo, as: :file %>
          <%=f.button :submit, "Post!", class: "btn-post"%>
    <% end %>
  </div>
</div>

app/views/pets/show.html.erb
<div class="container">
  <h1 class="text-center">About <%= @pet.name.upcase %> <i class="fas fa-heart"></i></h1>

  <div class="card-block">
      <h3 class="m-b-20 p-b-5 b-b-default f-w-600">Contact Info</h3>
      <div class="row">
          <div class="col-sm-6">
              <h6 class="m-b-10 f-w-600">Owner</h6>
              <h6 class="text-muted f-w-400"><%= link_to @pet.user.name, user_path(@pet.user) %></h6>
          </div>
          <div class="col-sm-6">
              <h6 class="m-b-10 f-w-600">Loction</h6>
              <h6 class="text-muted f-w-400"><%= @pet.user.location %></h6>
          </div>
      </div>
      <h3 class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600">Note from <%= @pet.user.name %></h3>
      <div class="row">
          <div class="col-sm-12 col-xl-12">
            <h6 class="text-muted f-w-400">
              <i class="fas fa-quote-left"></i> <%= @pet.description %></h6>
          </div>
      </div>
      <br>
      <br>
      <%= link_to 'Book a time with me!', new_pet_booking_path(@pet), class: 'btn btn-confirm' %>

  <div class="card-product">
  <%= cl_image_tag @pet.user.photo.key, class: "avatar-square" %>
  <div class="card-product-infos">

    <p><i class="fas fa-quote-left"></i> <%= @pet.description %></p>
  </div>

  </div>

  <h6 class="text-muted text-right"><%= @pet.species %>, <%= @pet.age %> year(s) old</h6>
  <div> <%= cl_image_tag @pet.photo.key, crop: :fill if @pet.photo.attached? %> </div>
  <br>
  <br>
  <%= link_to 'Back to the list', pets_path(@pet), class: 'btn' %>
  <br>
  <br>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright ">
    © The Barter Club 2020, all rights reserved <i class="fas fa-paw"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/pets", class: "navbar-brand" do %>
    <%= image_tag "logo-petogether.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <% if user_signed_in? && current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

            <%= link_to "My page", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
    <h1 class="text-center">Edit profile</h1>

  <%= simple_form_for(@user) do |f| %>
    <%= f.input :name, html5: true %>
    <%= f.input :location, html5: true %>
    <%= f.input :bio, html5: true %>
    <%= f.button :submit, "Update your profile", class: "btn-confirm" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container text-center">
  <h1 class="">My Page <i class="fas fa-heart"></i></h1>
</div>

<div class="container" >
  <h3 class="m-b-20 p-b-5 b-b-default f-w-600 user-header">Profile</h3>
    <div class="row d-flex justify-content-center">
        <div class="col-xl-12 col-md-12 pl-0 pr-0">
            <div class="card user-card-full">
                <div class="row m-l-0 m-r-0">
                    <div class="col-sm-4 bg-c-lite-green user-profile">
                        <div class="card-block text-center text-white">
                            <div class="m-b-25"><%= cl_image_tag @user.photo.key, height: 120, width: 120, crop: :fill, class:"rounded-circle" %></div>
                            <h2 class="f-w-600"><%=@user.name %></h2>

                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="card-block">
                            <p class="m-b-20 p-b-5 b-b-default f-w-600">Contact Info</p>
                            <div class="row">
                                <div class="col-sm-6">
                                    <h6 class="m-b-10 f-w-600">Lives in</h6>
                                    <h6 class="text-muted f-w-400"><%=@user.location %></h6>
                                </div>
                                <div class="col-sm-6">
                                    <h6 class="m-b-10 f-w-600">Email</h6>
                                    <h6 class="text-muted f-w-400"><%=@user.email %></h6>
                                </div>
                            </div>
                            <p class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600">About Me</p>
                            <div class="row">
                                <div class="col-sm-12 col-xl-12">
                                  <h6 class="text-muted f-w-400"><%=@user.bio %></h6>
                                </div>
                            </div>
                            <p class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600"></p>
                            <div class="row">
                              <div class="col-sm-12 col-xl-12 user-profile-btn">
                                <% if @user === current_user %>
                                  <%= link_to "Edit my profile", edit_user_path(@user), class:"btn" %>
                                <% end %>
                              </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <h3 class="m-b-20 p-b-5 b-b-default f-w-600 user-header"><%= @user.name.capitalize %>'s pets</h3>
    <div class="justify-content-center">
    <div class="cards justify-content-center mt-3">
      <% @pets.each do |pet| %>
        <div class="card-trip">
          <div class="card-trip-infos">
            <div>
              <h2><%= pet.name %></h2>
              <p><%= pet.species %></p>
              <p><%= pet.description %></p>
              <%= link_to pet_path(pet) do %>
                <%= cl_image_tag pet.photo.key %>
                <% end %>
            </div>
          </div>
            <%= link_to "", pet_path(pet), class: 'card-link' %>
        </div>
      <% end %>
    </div>
    </div>
</div>


<div class="container">
  <% if @user === current_user %>
    <h3 class="m-b-20 p-b-5 b-b-default f-w-600 user-header">All your bookings</h3>
    <ul class="list-group list-group-flush">
    <% @bookings.each do |b| %>
        <% if b.user === current_user %>
            <li class="list-group-item">
              <div class="row">
              <div class="col-sm-8">
                <i class="m-b-10 f-w-600 fas fa-paw"> <%= b.pet.name %> </i> the <%= b.pet.species %>
                <p class="text-muted f-w-400"><%= b.start_date %> ~ <%= b.end_date %></p>
              </div>
                <% if @user === current_user %>
                <div class="col-sm-4">
                <%= link_to 'edit', edit_pet_booking_path(pet_id: b.pet, id: b), class: 'btn' %>
                <%= link_to 'delete',
                booking_path(b),
                method: :delete,
                data: {confirm: "Are you sure?"}, class: 'btn'
               %>
                </div>
               <% end %>
            </div>
            </li>
        <% end %>
    <% end %>
  </ul>
  <% end %>
</div>